modLoader="javafml" #mandatory

loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL="https://github.com/KingOfTheGamesYT/DangerZone/issues" #optional

[[mods]] #mandatory
itemIcon="dangerzone:cake_sword"

configBackground="dangerzone:textures/blocks/kyuubi_egg_ore.png"

modId="dangerzone" #mandatory

version="3.1.3" #mandatory

displayName="DangerZone" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://officialteamolympus.weebly.com/craftzone.html" #optional

logoFile="dangerzone.png" #optional

credits="Thanks for this mod goes to TheyCallMeDanger for making DangerZone the game" #optional

authors=["RedRoseWarrior1 aka DevMaster1015","coolGi007"] #optional

description='''
Brings DangerZone to Minecraft
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.dangerzone]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[36,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.dangerzone]]
    modId="minecraft"
    mandatory=true
versionRange="[1.16.5,1.17]"
    ordering="NONE"
    side="BOTH"

# Rises the limit for health, without it the mobs with above 512 health will have 512 health
[[dependencies.dangerzone]]
modId="attributefix"
mandatory=false
versionRange="[10.1.2,)"
ordering="NONE"
side="BOTH"
